wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1709572733.85741
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 0.009
batch_size:
  desc: null
  value: 5
epoch:
  desc: null
  value: 4
gae_lambda:
  desc: null
  value: 0.95
games:
  desc: null
  value: 1000
gamma:
  desc: null
  value: 0.99
policy_clip:
  desc: null
  value: 0.2
pretrain:
  desc: null
  value: true
render:
  desc: null
  value: human
save_interval:
  desc: null
  value: 10
seed:
  desc: null
  value: 5
train_freq:
  desc: null
  value: 20
transfer_train:
  desc: null
  value: false
write:
  desc: null
  value: true
