wandb_version: 1

write:
  desc: null
  value: true
render:
  desc: null
  value: human
seed:
  desc: null
  value: 5
save_interval:
  desc: null
  value: 10
eval_interval:
  desc: null
  value: 5
random_steps:
  desc: null
  value: 100
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
exp_noise:
  desc: null
  value: 1.0
buffersize:
  desc: null
  value: 100000.0
target_freq:
  desc: null
  value: 100
hardtarget:
  desc: null
  value: false
anneal_frac:
  desc: null
  value: 200000.0
train_freq:
  desc: null
  value: 1
pretrain:
  desc: null
  value: false
transfer_train:
  desc: null
  value: true
games:
  desc: null
  value: 25
epoch:
  desc: null
  value: 2
good_agents_source:
  desc: null
  value: 2
good_agents_target:
  desc: null
  value: 3
train_all_agents:
  desc: null
  value: true
best_good_agent:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709890311.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
